#!/bin/sh /etc/rc.common
# IPsec Ping Monitor Init Script

START=99
STOP=10

USE_PROCD=1
PROG=/usr/sbin/ipsec-ping-monitor.sh

start_service() {
	local enabled=$(uci get ipsec.health.enabled 2>/dev/null)

	# Only start if enabled
	[ "$enabled" != "1" ] && return 0

	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	rm -f /var/run/ipsec-ping-monitor.state
}

reload_service() {
	stop
	start
}
